/**
 * Offline university search — replaces dead Hipolabs API.
 */
(function (global) {
    const UNIVERSITIES = [
        { name: 'University of Toronto', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'York University', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Toronto Metropolitan University', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'McGill University', country: 'Canada', 'state-province': 'Quebec' },
        { name: 'University of British Columbia', country: 'Canada', 'state-province': 'British Columbia' },
        { name: 'University of Waterloo', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'McMaster University', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Queen\'s University', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Western University', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'University of Ottawa', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Carleton University', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Simon Fraser University', country: 'Canada', 'state-province': 'British Columbia' },
        { name: 'University of Alberta', country: 'Canada', 'state-province': 'Alberta' },
        { name: 'University of Calgary', country: 'Canada', 'state-province': 'Alberta' },
        { name: 'Dalhousie University', country: 'Canada', 'state-province': 'Nova Scotia' },
        { name: 'University of Manitoba', country: 'Canada', 'state-province': 'Manitoba' },
        { name: 'University of Saskatchewan', country: 'Canada', 'state-province': 'Saskatchewan' },
        { name: 'Concordia University', country: 'Canada', 'state-province': 'Quebec' },
        { name: 'Université de Montréal', country: 'Canada', 'state-province': 'Quebec' },
        { name: 'Harvard University', country: 'United States', 'state-province': 'Massachusetts' },
        { name: 'Stanford University', country: 'United States', 'state-province': 'California' },
        { name: 'Massachusetts Institute of Technology', country: 'United States', 'state-province': 'Massachusetts' },
        { name: 'University of California, Berkeley', country: 'United States', 'state-province': 'California' },
        { name: 'University of California, Los Angeles', country: 'United States', 'state-province': 'California' },
        { name: 'Columbia University', country: 'United States', 'state-province': 'New York' },
        { name: 'New York University', country: 'United States', 'state-province': 'New York' },
        { name: 'University of Michigan', country: 'United States', 'state-province': 'Michigan' },
        { name: 'University of Texas at Austin', country: 'United States', 'state-province': 'Texas' },
        { name: 'University of Florida', country: 'United States', 'state-province': 'Florida' },
        { name: 'University of Washington', country: 'United States', 'state-province': 'Washington' },
        { name: 'Georgia Institute of Technology', country: 'United States', 'state-province': 'Georgia' },
        { name: 'University of Illinois Urbana-Champaign', country: 'United States', 'state-province': 'Illinois' },
        { name: 'Pennsylvania State University', country: 'United States', 'state-province': 'Pennsylvania' },
        { name: 'Ohio State University', country: 'United States', 'state-province': 'Ohio' },
        { name: 'University of Wisconsin-Madison', country: 'United States', 'state-province': 'Wisconsin' },
        { name: 'Purdue University', country: 'United States', 'state-province': 'Indiana' },
        { name: 'Arizona State University', country: 'United States', 'state-province': 'Arizona' },
        { name: 'University of Arizona', country: 'United States', 'state-province': 'Arizona' },
        { name: 'Boston University', country: 'United States', 'state-province': 'Massachusetts' },
        { name: 'Northeastern University', country: 'United States', 'state-province': 'Massachusetts' },
        { name: 'University of Southern California', country: 'United States', 'state-province': 'California' },
        { name: 'University of North Carolina at Chapel Hill', country: 'United States', 'state-province': 'North Carolina' },
        { name: 'Duke University', country: 'United States', 'state-province': 'North Carolina' },
        { name: 'Cornell University', country: 'United States', 'state-province': 'New York' },
        { name: 'Princeton University', country: 'United States', 'state-province': 'New Jersey' },
        { name: 'Yale University', country: 'United States', 'state-province': 'Connecticut' },
        { name: 'University of Pennsylvania', country: 'United States', 'state-province': 'Pennsylvania' },
        { name: 'University of Virginia', country: 'United States', 'state-province': 'Virginia' },
        { name: 'University of Maryland', country: 'United States', 'state-province': 'Maryland' },
        { name: 'Texas A&M University', country: 'United States', 'state-province': 'Texas' },
        { name: 'University of Colorado Boulder', country: 'United States', 'state-province': 'Colorado' },
        { name: 'University of Minnesota', country: 'United States', 'state-province': 'Minnesota' },
        { name: 'Indiana University Bloomington', country: 'United States', 'state-province': 'Indiana' },
        { name: 'Michigan State University', country: 'United States', 'state-province': 'Michigan' },
        { name: 'Rutgers University', country: 'United States', 'state-province': 'New Jersey' },
        { name: 'University of Georgia', country: 'United States', 'state-province': 'Georgia' },
        { name: 'University of Pittsburgh', country: 'United States', 'state-province': 'Pennsylvania' },
        { name: 'Virginia Tech', country: 'United States', 'state-province': 'Virginia' },
        { name: 'University of Iowa', country: 'United States', 'state-province': 'Iowa' },
        { name: 'University of Oregon', country: 'United States', 'state-province': 'Oregon' },
        { name: 'University of Utah', country: 'United States', 'state-province': 'Utah' },
        { name: 'University of Kansas', country: 'United States', 'state-province': 'Kansas' },
        { name: 'University of Missouri', country: 'United States', 'state-province': 'Missouri' },
        { name: 'University of Connecticut', country: 'United States', 'state-province': 'Connecticut' },
        { name: 'University of South Florida', country: 'United States', 'state-province': 'Florida' },
        { name: 'Florida State University', country: 'United States', 'state-province': 'Florida' },
        { name: 'University of Central Florida', country: 'United States', 'state-province': 'Florida' },
        { name: 'San Diego State University', country: 'United States', 'state-province': 'California' },
        { name: 'University of Nevada, Las Vegas', country: 'United States', 'state-province': 'Nevada' },
        { name: 'Temple University', country: 'United States', 'state-province': 'Pennsylvania' },
        { name: 'George Washington University', country: 'United States', 'state-province': 'District of Columbia' },
        { name: 'American University', country: 'United States', 'state-province': 'District of Columbia' },
        { name: 'Howard University', country: 'United States', 'state-province': 'District of Columbia' },
        { name: 'University of Houston', country: 'United States', 'state-province': 'Texas' },
        { name: 'University of Cincinnati', country: 'United States', 'state-province': 'Ohio' },
        { name: 'University of Tennessee', country: 'United States', 'state-province': 'Tennessee' },
        { name: 'University of Kentucky', country: 'United States', 'state-province': 'Kentucky' },
        { name: 'Louisiana State University', country: 'United States', 'state-province': 'Louisiana' },
        { name: 'University of Oklahoma', country: 'United States', 'state-province': 'Oklahoma' },
        { name: 'University of New Mexico', country: 'United States', 'state-province': 'New Mexico' },
        { name: 'University of Hawaii at Manoa', country: 'United States', 'state-province': 'Hawaii' },
        { name: 'University of Alaska Fairbanks', country: 'United States', 'state-province': 'Alaska' },
        { name: 'University of Rhode Island', country: 'United States', 'state-province': 'Rhode Island' },
        { name: 'University of New Hampshire', country: 'United States', 'state-province': 'New Hampshire' },
        { name: 'University of Vermont', country: 'United States', 'state-province': 'Vermont' },
        { name: 'University of Maine', country: 'United States', 'state-province': 'Maine' },
        { name: 'University of Delaware', country: 'United States', 'state-province': 'Delaware' },
        { name: 'University of Nebraska-Lincoln', country: 'United States', 'state-province': 'Nebraska' },
        { name: 'University of Arkansas', country: 'United States', 'state-province': 'Arkansas' },
        { name: 'University of Mississippi', country: 'United States', 'state-province': 'Mississippi' },
        { name: 'University of Alabama', country: 'United States', 'state-province': 'Alabama' },
        { name: 'Auburn University', country: 'United States', 'state-province': 'Alabama' },
        { name: 'Clemson University', country: 'United States', 'state-province': 'South Carolina' },
        { name: 'University of South Carolina', country: 'United States', 'state-province': 'South Carolina' },
        { name: 'University of Notre Dame', country: 'United States', 'state-province': 'Indiana' },
        { name: 'Emory University', country: 'United States', 'state-province': 'Georgia' },
        { name: 'Vanderbilt University', country: 'United States', 'state-province': 'Tennessee' },
        { name: 'Rice University', country: 'United States', 'state-province': 'Texas' },
        { name: 'Baylor University', country: 'United States', 'state-province': 'Texas' },
        { name: 'Brigham Young University', country: 'United States', 'state-province': 'Utah' },
        { name: 'Georgetown University', country: 'United States', 'state-province': 'District of Columbia' },
        { name: 'Johns Hopkins University', country: 'United States', 'state-province': 'Maryland' },
        { name: 'Carnegie Mellon University', country: 'United States', 'state-province': 'Pennsylvania' },
        { name: 'Brown University', country: 'United States', 'state-province': 'Rhode Island' },
        { name: 'Dartmouth College', country: 'United States', 'state-province': 'New Hampshire' },
        { name: 'University of Chicago', country: 'United States', 'state-province': 'Illinois' },
        { name: 'Northwestern University', country: 'United States', 'state-province': 'Illinois' },
        { name: 'Washington University in St. Louis', country: 'United States', 'state-province': 'Missouri' },
        { name: 'Case Western Reserve University', country: 'United States', 'state-province': 'Ohio' },
        { name: 'Rensselaer Polytechnic Institute', country: 'United States', 'state-province': 'New York' },
        { name: 'Rochester Institute of Technology', country: 'United States', 'state-province': 'New York' },
        { name: 'Syracuse University', country: 'United States', 'state-province': 'New York' },
        { name: 'University at Buffalo', country: 'United States', 'state-province': 'New York' },
        { name: 'Stony Brook University', country: 'United States', 'state-province': 'New York' },
        { name: 'University of California, San Diego', country: 'United States', 'state-province': 'California' },
        { name: 'University of California, Davis', country: 'United States', 'state-province': 'California' },
        { name: 'University of California, Irvine', country: 'United States', 'state-province': 'California' },
        { name: 'University of California, Santa Barbara', country: 'United States', 'state-province': 'California' },
        { name: 'California Institute of Technology', country: 'United States', 'state-province': 'California' },
        { name: 'Pepperdine University', country: 'United States', 'state-province': 'California' },
        { name: 'Loyola Marymount University', country: 'United States', 'state-province': 'California' },
        { name: 'Chapman University', country: 'United States', 'state-province': 'California' },
        { name: 'DePaul University', country: 'United States', 'state-province': 'Illinois' },
        { name: 'Loyola University Chicago', country: 'United States', 'state-province': 'Illinois' },
        { name: 'Marquette University', country: 'United States', 'state-province': 'Wisconsin' },
        { name: 'University of Denver', country: 'United States', 'state-province': 'Colorado' },
        { name: 'Colorado State University', country: 'United States', 'state-province': 'Colorado' },
        { name: 'University of Arizona Global Campus', country: 'United States', 'state-province': 'Arizona' },
        { name: 'Arizona State University Downtown Phoenix', country: 'United States', 'state-province': 'Arizona' },
        { name: 'Seneca College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Humber College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'George Brown College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Sheridan College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Fanshawe College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Conestoga College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Mohawk College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Niagara College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Centennial College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Algonquin College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Durham College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Lambton College', country: 'Canada', 'state-province': 'Ontario' },
        { name: 'Langara College', country: 'Canada', 'state-province': 'British Columbia' },
        { name: 'Douglas College', country: 'Canada', 'state-province': 'British Columbia' },
        { name: 'British Columbia Institute of Technology', country: 'Canada', 'state-province': 'British Columbia' },
        { name: 'Red River College Polytechnic', country: 'Canada', 'state-province': 'Manitoba' },
        { name: 'SAIT Polytechnic', country: 'Canada', 'state-province': 'Alberta' },
        { name: 'Northern Alberta Institute of Technology', country: 'Canada', 'state-province': 'Alberta' },
        { name: 'NSCC', country: 'Canada', 'state-province': 'Nova Scotia' }
    ];

    function normalize(str) {
        return (str || '').toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
    }

    function search(query, limit = 10) {
        const q = normalize(query);
        if (!q || q.length < 2) return [];

        return UNIVERSITIES.filter((uni) => {
            const hay = normalize(`${uni.name} ${uni.country} ${uni['state-province'] || ''}`);
            return hay.includes(q) || q.split(' ').every((word) => hay.includes(word));
        }).slice(0, limit);
    }

    global.UniversitySearch = { search, list: UNIVERSITIES };
})(typeof window !== 'undefined' ? window : global);
